# Generated by Django 5.1.3 on 2024-11-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('In processing', 'In processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20),
        ),
    ]
