# Generated by Django 5.1.3 on 2024-11-10 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='application_status',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_status', to='app.application'),
        ),
    ]
