# Generated by Django 5.1.3 on 2024-11-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_applicant_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='application_status',
        ),
    ]
