# Generated by Django 5.1.3 on 2024-11-10 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_applicant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_documents', to='app.application'),
        ),
    ]
