# Generated by Django 5.1.3 on 2024-11-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_document_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='application',
        ),
    ]
