# Generated by Django 5.1.3 on 2024-11-10 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_applicant_user_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='documents',
        ),
        migrations.AddField(
            model_name='application',
            name='documents',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.document'),
        ),
    ]
