# Generated by Django 5.1.3 on 2024-11-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_application_documents_application_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='documents',
        ),
        migrations.CreateModel(
            name='DocumentApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.document')),
            ],
        ),
    ]
