# Generated by Django 5.1.3 on 2024-12-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_application_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.RemoveField(
            model_name='application',
            name='operator',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
